/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/********************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED
 * DESCRIPTION:
 *   Virtual PC operating system API
 ********************************************************************************/
#undef INCLUDE_ASCET_SE_INTPOL
#include "a_basdef.h"
#include "protocol\l1\p_sysdef.h"
#include "protocol\l1\p_protl1.h"
#include "protocol\l1\p_stdeb.h"
#include "a_tardef.h"
#include "a_contai.h"
#include "t_croman.h"
#include "t_sglow.h"
#include "t_sgman.h"
#include "vrtaDevices.h"
#include "IntecrioDeviceInfo.h"

extern void Tick_etasCounter(void);

#ifdef XCP_SLAVE
	extern uint32 Xcp_Event (uint32 eventId, uint32 doDaq);
	#define XCP_DAQ_Task0 Xcp_Event(0,0);
	#define XCP_STIM_Task0 Xcp_Event(0,1);
#else
	#define XCP_DAQ_Task0
	#define XCP_STIM_Task0
#endif

#ifdef L1_PROTOCOL
	#define SIGNAL_GENERATOR_HOOK_Task0 \
	sgHook(1); \
	crossbarHook(1,0);
#else
	#define SIGNAL_GENERATOR_HOOK_Task0
#endif

#define XCP_NUMBER_OF_EVENTS 1
