/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.ACC
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCCF_MYCAR_ACC_AUTOMATIC_PRIVATE
#define ESDL_MYCCF_MYCAR_ACC_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define brake_VAL self->MyCCF_myCar_ACC_Automatic_RAM->brake
#define on_VAL self->MyCCF_myCar_ACC_Automatic_RAM->on
#define accOn_VAL self->MyCCF_myCar_ACC_Automatic_RAM->accOn
#define sm_VAL self->MyCCF_myCar_ACC_Automatic_RAM->sm
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCCF_MYCAR_ACC_AUTOMATIC_PRIVATE */

