/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.MyTurn
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "MyCCF_myCar_MyTurn_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define bearing_VAL (self->MyCCF_myCar_MyTurn_Automatic_RAM->bearing)
#define D_VAL (self->MyCCF_myCar_MyTurn_Automatic_CAL_MEM->D)
#define dpi_VAL (self->MyCCF_myCar_MyTurn_Automatic_RAM->dpi)
#define pi_VAL (self->MyCCF_myCar_MyTurn_Automatic_RAM->pi)
#define x_VAL (self->MyCCF_myCar_MyTurn_Automatic_RAM->x)
#define y_VAL (self->MyCCF_myCar_MyTurn_Automatic_RAM->y)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'MyCCF_myCar_MyTurn_Automatic_move'
 * ----------------------------------------------------------------------------
 * model name:...................................'move'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void MyCCF_myCar_MyTurn_Automatic_move (
               const struct MyCCF_myCar_MyTurn_Automatic * self,
   /* IN    */ const float32                               beta,
   /* IN    */ const float32                               v,
   /* IN    */ const float32                               mydt
   )
{
   bearing_VAL
      = bearing_VAL + ((((D_VAL == 0.0F) ? v : (v / D_VAL))) * (float32)tan((float64)beta) * mydt * 7.71604938271605e-2F);
   if (bearing_VAL > pi_VAL)
   {
      bearing_VAL = bearing_VAL - dpi_VAL;
   } /* end if */
   if (bearing_VAL < -pi_VAL)
   {
      bearing_VAL = bearing_VAL + dpi_VAL;
   } /* end if */
   x_VAL
      = x_VAL + (v * (float32)cos((float64)bearing_VAL) * mydt * 2.77777777777778e-1F);
   y_VAL
      = y_VAL + (v * (float32)sin((float64)bearing_VAL) * mydt * 2.77777777777778e-1F);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'MyCCF_myCar_MyTurn_Automatic_move'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



