/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.myDrive_3
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "MyCCF_myCar_myDrive_3_Automatic.h"
#include "ESDL_Linear_Interpolation.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define AirFriction_REF (&(self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->AirFriction))
#define bearing_VAL (self->MyCCF_myCar_myDrive_3_Automatic_RAM->bearing)
#define BrakeMomentum_REF (&(self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->BrakeMomentum))
#define dh_VAL (self->MyCCF_myCar_myDrive_3_Automatic_RAM->dh)
#define dist_VAL (self->MyCCF_myCar_myDrive_3_Automatic_RAM->dist)
#define ds_VAL (self->MyCCF_myCar_myDrive_3_Automatic_RAM->ds)
#define EngineMomentum_REF (&(self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->EngineMomentum))
#define h_VAL (self->MyCCF_myCar_myDrive_3_Automatic_RAM->h)
#define Landscape_REF (&(self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->Landscape))
#define momentum_VAL (self->MyCCF_myCar_myDrive_3_Automatic_RAM->momentum)
#define MyTurn_instance_REF (&(self->MyTurn_instance))
#define TrackSize_VAL (self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->TrackSize)
#define v_VAL (self->MyCCF_myCar_myDrive_3_Automatic_RAM->v)
#define x_VAL (self->MyCCF_myCar_myDrive_3_Automatic_RAM->x)
#define y_VAL (self->MyCCF_myCar_myDrive_3_Automatic_RAM->y)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'MyCCF_myCar_myDrive_3_Automatic_move'
 * ----------------------------------------------------------------------------
 * model name:...................................'move'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void MyCCF_myCar_myDrive_3_Automatic_move (
               const struct MyCCF_myCar_myDrive_3_Automatic * self,
   /* IN    */ const float32                                  powerCtrl,
   /* IN    */ const float32                                  brakeCtrl,
   /* IN    */ const float32                                  mydt,
   /* IN    */ const float32                                  myg,
   /* IN    */ const float32                                  delta
   )
{
   if (dist_VAL > TrackSize_VAL)
   {
      dist_VAL = 0.0F;
   } /* end if */
   momentum_VAL
      = ESDL_Linear_CharTable2_getAt_r32r32r32((EngineMomentum_REF)->xSize, (EngineMomentum_REF)->xDist, (EngineMomentum_REF)->ySize, (EngineMomentum_REF)->yDist, (EngineMomentum_REF)->values, powerCtrl, v_VAL);
   dist_VAL = ds_VAL + dist_VAL;
   dh_VAL
      = h_VAL - ESDL_Linear_CharTable1_getAt_r32r32((Landscape_REF)->xSize, (Landscape_REF)->xDist, (Landscape_REF)->values, dist_VAL);
   h_VAL
      = ESDL_Linear_CharTable1_getAt_r32r32((Landscape_REF)->xSize, (Landscape_REF)->xDist, (Landscape_REF)->values, dist_VAL);
   v_VAL
      = ((ESDL_Linear_CharTable1_getAt_r32r32((BrakeMomentum_REF)->xSize, (BrakeMomentum_REF)->xDist, (BrakeMomentum_REF)->values, brakeCtrl) + momentum_VAL + ESDL_Linear_CharTable1_getAt_r32r32((AirFriction_REF)->xSize, (AirFriction_REF)->xDist, (AirFriction_REF)->values, v_VAL) + (myg * (((ds_VAL == 0.0F) ? dh_VAL : (dh_VAL / ds_VAL))) * 9.81F)) * mydt * 3.6F) + v_VAL;
   ds_VAL = v_VAL * mydt * 2.77777777777778e-1F;
   MyCCF_myCar_MyTurn_Automatic_move(MyTurn_instance_REF, delta, v_VAL, mydt);
   bearing_VAL
      = self->MyTurn_instance.MyCCF_myCar_MyTurn_Automatic_RAM->bearing;
   x_VAL = self->MyTurn_instance.MyCCF_myCar_MyTurn_Automatic_RAM->x;
   y_VAL = self->MyTurn_instance.MyCCF_myCar_MyTurn_Automatic_RAM->y;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'MyCCF_myCar_myDrive_3_Automatic_move'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



