/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.resources.CarMessages
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCCF_RESOURCES_CARMESSAGES_AUTOMATIC_H_
#define _ASD_MYCCF_RESOURCES_CARMESSAGES_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/* component structure for module MYCCF_RESOURCES_CARMESSAGES_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ......MyCCF_resources_CarMessages_Automatic */
#define _MyCCF_resources_CarMessages_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module MyCCF_resources_CarMessages_Automatic
 ******************************************************************************/


/* declaration of messages */
extern float32 MyCCF_resources_CarMessages_bearing;
extern float32 MyCCF_resources_CarMessages_brake;
extern float32 MyCCF_resources_CarMessages_power;
extern float32 MyCCF_resources_CarMessages_steering;
extern float32 MyCCF_resources_CarMessages_time;
extern float32 MyCCF_resources_CarMessages_v;
extern float32 MyCCF_resources_CarMessages_x;
extern float32 MyCCF_resources_CarMessages_y;


#endif /* _ASD_MYCCF_RESOURCES_CARMESSAGES_AUTOMATIC_H_ */
