/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.Control
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCCF_MYCAR_CONTROL_AUTOMATIC_PRIVATE
#define ESDL_MYCCF_MYCAR_CONTROL_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define ACC_instance_VAL MyCCF_myCar_Control.ACC_instance
#define ACC_instance_REF &(MyCCF_myCar_Control.ACC_instance)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCCF_MYCAR_CONTROL_AUTOMATIC_PRIVATE */

