/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.myDrive_3
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCCF_MYCAR_MYDRIVE_3_AUTOMATIC_PRIVATE
#define ESDL_MYCCF_MYCAR_MYDRIVE_3_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define BrakeMomentum_VAL self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->BrakeMomentum
#define BrakeMomentum_REF &(self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->BrakeMomentum)
#define EngineMomentum_VAL self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->EngineMomentum
#define EngineMomentum_REF &(self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->EngineMomentum)
#define AirFriction_VAL self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->AirFriction
#define AirFriction_REF &(self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->AirFriction)
#define Landscape_VAL self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->Landscape
#define Landscape_REF &(self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->Landscape)
#define h_VAL self->MyCCF_myCar_myDrive_3_Automatic_RAM->h
#define dh_VAL self->MyCCF_myCar_myDrive_3_Automatic_RAM->dh
#define ds_VAL self->MyCCF_myCar_myDrive_3_Automatic_RAM->ds
#define momentum_VAL self->MyCCF_myCar_myDrive_3_Automatic_RAM->momentum
#define dist_VAL self->MyCCF_myCar_myDrive_3_Automatic_RAM->dist
#define TrackSize_VAL self->MyCCF_myCar_myDrive_3_Automatic_CAL_MEM->TrackSize
#define v_VAL self->MyCCF_myCar_myDrive_3_Automatic_RAM->v
#define MyTurn_instance_VAL self->MyTurn_instance
#define MyTurn_instance_REF &(self->MyTurn_instance)
#define x_VAL self->MyCCF_myCar_myDrive_3_Automatic_RAM->x
#define y_VAL self->MyCCF_myCar_myDrive_3_Automatic_RAM->y
#define bearing_VAL self->MyCCF_myCar_myDrive_3_Automatic_RAM->bearing
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCCF_MYCAR_MYDRIVE_3_AUTOMATIC_PRIVATE */

