/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.resources.DriverMessages
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "MyCCF_resources_DriverMessages_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'MyCCF_resources_DriverMessages'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/






/******************************************************************************
 * BEGIN: DEFINITION OF MESSAGES
 * ----------------------------------------------------------------------------
 * Total size is [bytes]:........................16
 * ---------------------------------------------------------------------------*/
/* messages of memory class:............................................'RAM' */
/* messages of size [bytes]:................................................4 */
/* modelled as 'MyCCF_resources_DriverMessages_brake' */
float32 MyCCF_resources_DriverMessages_brake = 0.0F;
/* modelled as 'MyCCF_resources_DriverMessages_power' */
float32 MyCCF_resources_DriverMessages_power = 0.0F;
/* modelled as 'MyCCF_resources_DriverMessages_soll' */
float32 MyCCF_resources_DriverMessages_soll = 40.0F;
/* messages of size [bytes]:................................................1 */
/* modelled as 'MyCCF_resources_DriverMessages_decrement' */
uint8 MyCCF_resources_DriverMessages_decrement = false;
/* modelled as 'MyCCF_resources_DriverMessages_display' */
uint8 MyCCF_resources_DriverMessages_display = false;
/* modelled as 'MyCCF_resources_DriverMessages_increment' */
uint8 MyCCF_resources_DriverMessages_increment = false;
/* modelled as 'MyCCF_resources_DriverMessages_on' */
uint8 MyCCF_resources_DriverMessages_on = false;
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MESSAGES
 ******************************************************************************/



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



