/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.myDrive_3
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCCF_MYCAR_MYDRIVE_3_AUTOMATIC_H_
#define _ASD_MYCCF_MYCAR_MYDRIVE_3_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "MyCCF_myCar_MyTurn_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'MyCCF_myCar_myDrive_3_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_myDrive_3_Automatic_CAL_MEM_SUBSTRUCT {
   float32 TrackSize;
   struct MyCCF_myCar_MyTurn_Automatic_CAL_MEM_SUBSTRUCT MyTurn_instance;
   struct CharTable1D_float32_6_float32_6 AirFriction;
   struct CharTable1D_float32_6_float32_6 BrakeMomentum;
   struct CharTable2D_float32_6_float32_6_float32_36 EngineMomentum;
   struct CharTable1D_float32_128_float32_128 Landscape;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'MyCCF_myCar_myDrive_3_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'MyCCF_myCar_myDrive_3_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_myDrive_3_Automatic_RAM_SUBSTRUCT {
   float32 bearing;
   float32 dh;
   float32 dist;
   float32 ds;
   float32 h;
   float32 momentum;
   float32 v;
   float32 x;
   float32 y;
   struct MyCCF_myCar_MyTurn_Automatic_RAM_SUBSTRUCT MyTurn_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'MyCCF_myCar_myDrive_3_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'MyCCF_myCar_myDrive_3_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_myDrive_3_Automatic {
   struct MyCCF_myCar_myDrive_3_Automatic_CAL_MEM_SUBSTRUCT * MyCCF_myCar_myDrive_3_Automatic_CAL_MEM;
   struct MyCCF_myCar_myDrive_3_Automatic_RAM_SUBSTRUCT * MyCCF_myCar_myDrive_3_Automatic_RAM;
   struct MyCCF_myCar_MyTurn_Automatic MyTurn_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'MyCCF_myCar_myDrive_3_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ............MyCCF_myCar_myDrive_3_Automatic */
#define _MyCCF_myCar_myDrive_3_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class MyCCF_myCar_myDrive_3_Automatic
 ******************************************************************************/
extern void MyCCF_myCar_myDrive_3_Automatic_move (
               const struct MyCCF_myCar_myDrive_3_Automatic * self,
   /* IN    */ const float32                                  powerCtrl,
   /* IN    */ const float32                                  brakeCtrl,
   /* IN    */ const float32                                  mydt,
   /* IN    */ const float32                                  myg,
   /* IN    */ const float32                                  delta
   );



#endif /* _ASD_MYCCF_MYCAR_MYDRIVE_3_AUTOMATIC_H_ */
