/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.Driver
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCCF_MYCAR_DRIVER_AUTOMATIC_H_
#define _ASD_MYCCF_MYCAR_DRIVER_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'MyCCF_myCar_Driver_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_Driver_Automatic_CAL_MEM_SUBSTRUCT {
   float32 brake;
   uint8 controlACC;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'MyCCF_myCar_Driver_Automatic'
 ******************************************************************************/


/* component structure for module MYCCF_MYCAR_DRIVER_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...............MyCCF_myCar_Driver_Automatic */
#define _MyCCF_myCar_Driver_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'MyCCF_myCar_Driver_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct MyCCF_myCar_Driver_Automatic_CAL_MEM_SUBSTRUCT MyCCF_myCar_Driver_CAL_MEM;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module MyCCF_myCar_Driver_Automatic
 ******************************************************************************/
extern void MyCCF_myCar_Driver_Automatic_calc (void);



#endif /* _ASD_MYCCF_MYCAR_DRIVER_AUTOMATIC_H_ */
