/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.myCar
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "MyCCF_myCar_myCar_Automatic.h"
#include "ACC_Experiment_Automatic.h"
#include "MyCCF_resources_CarMessages_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'MyCCF_myCar_myCar_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'MyCCF_myCar_myCar'
 * data set:.....................................'MYCCF_MYCAR_MYCAR_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_myCar_Automatic_CAL_MEM_SUBSTRUCT MyCCF_myCar_myCar_CAL_MEM = {
   /* struct element:'MyCCF_myCar_myCar_CAL_MEM.g' (modeled as:'g.MyCCF_myCar_myCar') */
   9.81F,
   /* substruct: MyCCF_myCar_myCar_CAL_MEM.myVehicle (modeled as:'myVehicle.MyCCF_myCar_myCar') */
   {
      /* struct element:'MyCCF_myCar_myCar_CAL_MEM.myVehicle.TrackSize' (modeled as:'TrackSize.myVehicle.MyCCF_myCar_myCar') */
      1000.0F,
      /* substruct: MyCCF_myCar_myCar_CAL_MEM.myVehicle.MyTurn_instance (modeled as:'MyTurn_instance.myVehicle.MyCCF_myCar_myCar') */
      {
         /* struct element:'MyCCF_myCar_myCar_CAL_MEM.myVehicle.MyTurn_instance.D' (modeled as:'D.MyTurn_instance.myVehicle.MyCCF_myCar_myCar') */
         2.85F
      },
      /* struct element:'MyCCF_myCar_myCar_CAL_MEM.myVehicle.AirFriction' (modeled as:'AirFriction.myVehicle.MyCCF_myCar_myCar') */
      {
         6U,
         {
            0.0F, 30.0F, 60.0F, 90.0F, 120.0F, 150.0F
         },
         {
            0.0F, -0.1F, -0.2F, -0.4F, -0.8F, -1.6F
         }
      },
      /* struct element:'MyCCF_myCar_myCar_CAL_MEM.myVehicle.BrakeMomentum' (modeled as:'BrakeMomentum.myVehicle.MyCCF_myCar_myCar') */
      {
         6U,
         {
            0.0F, 1.0F, 40.0F, 60.0F, 80.0F, 100.0F
         },
         {
            0.0F, 0.0F, -1.0F, -2.0F, -3.0F, -4.0F
         }
      },
      /* struct element:'MyCCF_myCar_myCar_CAL_MEM.myVehicle.EngineMomentum' (modeled as:'EngineMomentum.myVehicle.MyCCF_myCar_myCar') */
      {
         6U,
         6U,
         {
            0.0F, 5.0F, 20.0F, 60.126582278481F, 80.0F, 100.0F
         },
         {
            0.0F, 30.0F, 60.0F, 90.0F, 150.0F, 200.0F
         },
         {
            [12] = 8.49999999999999e-1F, [13] = 0.6F, [14] = 0.3F,
            [18] = 3.15F, [19] = 2.35F, [20] = 1.55F, [21] = 8.00000000000001e-1F, [22] =
            3.99999999999999e-1F,
            [24] = 4.5F, [25] = 3.6F, [26] = 2.7F, [27] = 1.5F, [28] = 0.9F,
            [30] = 5.0F, [31] = 4.5F, [32] = 3.80000000000001F, [33] = 2.8F, [34] = 1.9F
         }
      },
      /* struct element:'MyCCF_myCar_myCar_CAL_MEM.myVehicle.Landscape' (modeled as:'Landscape.myVehicle.MyCCF_myCar_myCar') */
      {
         128U,
         {
            0.0F, 100.0F, 145.569620253165F, 202.53164556962F, 221.518987341772F, 240.0F,
            259.493670886076F, 300.0F, 350.0F, 400.0F, 450.0F, 500.0F, 600.0F, 700.0F,
            750.0F, 800.0F, 810.0F, 850.0F, 900.0F, 1000.0F, 1100.0F, 1200.0F, 1300.0F,
            1400.0F, 1500.0F, 1600.0F, 1700.0F, 1800.0F, 1900.0F, 2000.0F, 2100.0F, 2200.0F,
            2300.0F, 2400.0F, 2500.0F, 2600.0F, 2700.0F, 2800.0F, 2900.0F, 3000.0F, 3100.0F,
            3200.0F, 3300.0F, 3400.0F, 3500.0F, 3600.0F, 3700.0F, 3800.0F, 3900.0F, 4000.0F,
            4100.0F, 4200.0F, 4300.0F, 4400.0F, 4500.0F, 4600.0F, 4700.0F, 4800.0F, 4900.0F,
            5000.0F, 5100.0F, 5200.0F, 5300.0F, 5400.0F, 5500.0F, 5600.0F, 5700.0F, 5800.0F,
            5900.0F, 6000.0F, 6100.0F, 6200.0F, 6300.0F, 6400.0F, 6500.0F, 6600.0F, 6700.0F,
            6800.0F, 6900.0F, 7000.0F, 7100.0F, 7200.0F, 7300.0F, 7400.0F, 7500.0F, 7600.0F,
            7700.0F, 7800.0F, 7900.0F, 8000.0F, 8100.0F, 8200.0F, 8300.0F, 8400.0F, 8500.0F,
            8600.0F, 8700.0F, 8800.0F, 8900.0F, 9000.0F, 9100.0F, 9200.0F, 9300.0F, 9400.0F,
            9500.0F, 9600.0F, 9700.0F, 9800.0F, 9900.0F, 10000.0F, 10100.0F, 10200.0F,
            10300.0F, 10400.0F, 10500.0F, 10600.0F, 10700.0F, 10800.0F, 10900.0F, 11000.0F,
            11100.0F, 11200.0F, 11300.0F, 11400.0F, 11500.0F, 11600.0F, 11700.0F, 11800.0F
         },
         {
            [1] = 4.0F, [2] = 7.125F, [3] = 10.375F, [4] = 10.75F, [5] = 10.5F, [6] = 9.0F,
            [7] = 5.375F, [8] = 2.625F, [9] = 0.625F, [10] = 1.25F, [11] = 0.625F, [14] =
            1.375F, [15] = 0.75F, [16] = 0.375F, [17] = 0.625F
         }
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'MyCCF_myCar_myCar_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'MyCCF_myCar_myCar_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'MyCCF_myCar_myCar'
 * data set:.....................................'MYCCF_MYCAR_MYCAR_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_myCar_Automatic_RAM_SUBSTRUCT MyCCF_myCar_myCar_RAM = {
   /* substruct: MyCCF_myCar_myCar_RAM.myVehicle (modeled as:'myVehicle.MyCCF_myCar_myCar') */
   {
      /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.bearing' (modeled as:'bearing.myVehicle.MyCCF_myCar_myCar') */
      0.0F,
      /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.dh' (modeled as:'dh.myVehicle.MyCCF_myCar_myCar') */
      0.0F,
      /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.dist' (modeled as:'dist.myVehicle.MyCCF_myCar_myCar') */
      0.0F,
      /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.ds' (modeled as:'ds.myVehicle.MyCCF_myCar_myCar') */
      0.0F,
      /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.h' (modeled as:'h.myVehicle.MyCCF_myCar_myCar') */
      0.0F,
      /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.momentum' (modeled as:'momentum.myVehicle.MyCCF_myCar_myCar') */
      0.0F,
      /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.v' (modeled as:'v.myVehicle.MyCCF_myCar_myCar') */
      0.0F,
      /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.x' (modeled as:'x.myVehicle.MyCCF_myCar_myCar') */
      0.0F,
      /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.y' (modeled as:'y.myVehicle.MyCCF_myCar_myCar') */
      0.0F,
      /* substruct: MyCCF_myCar_myCar_RAM.myVehicle.MyTurn_instance (modeled as:'MyTurn_instance.myVehicle.MyCCF_myCar_myCar') */
      {
         /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.MyTurn_instance.bearing' (modeled as:'bearing.MyTurn_instance.myVehicle.MyCCF_myCar_myCar') */
         0.0F,
         /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.MyTurn_instance.dpi' (modeled as:'dpi.MyTurn_instance.myVehicle.MyCCF_myCar_myCar') */
         6.28318531F,
         /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.MyTurn_instance.pi' (modeled as:'pi.MyTurn_instance.myVehicle.MyCCF_myCar_myCar') */
         3.141592653F,
         /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.MyTurn_instance.x' (modeled as:'x.MyTurn_instance.myVehicle.MyCCF_myCar_myCar') */
         0.0F,
         /* struct element:'MyCCF_myCar_myCar_RAM.myVehicle.MyTurn_instance.y' (modeled as:'y.MyTurn_instance.myVehicle.MyCCF_myCar_myCar') */
         0.0F
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'MyCCF_myCar_myCar_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'MyCCF_myCar_myCar'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'MyCCF_myCar_myCar'
 * data set:.....................................'MYCCF_MYCAR_MYCAR_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct MyCCF_myCar_myCar_Automatic MyCCF_myCar_myCar = {
   /* substruct: MyCCF_myCar_myCar.myVehicle (modeled as:'myVehicle.MyCCF_myCar_myCar') */
   {
      /* type descriptor pointer 'MyCCF_myCar_myDrive_3_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &MyCCF_myCar_myCar_CAL_MEM.myVehicle,
      /* type descriptor pointer 'MyCCF_myCar_myDrive_3_Automatic_RAM' for memory class substruct for 'RAM' */
      &MyCCF_myCar_myCar_RAM.myVehicle,
      /* substruct: MyCCF_myCar_myCar.myVehicle.MyTurn_instance (modeled as:'MyTurn_instance.myVehicle.MyCCF_myCar_myCar') */
      {
         /* type descriptor pointer 'MyCCF_myCar_MyTurn_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
         &MyCCF_myCar_myCar_CAL_MEM.myVehicle.MyTurn_instance,
         /* type descriptor pointer 'MyCCF_myCar_MyTurn_Automatic_RAM' for memory class substruct for 'RAM' */
         &MyCCF_myCar_myCar_RAM.myVehicle.MyTurn_instance
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'MyCCF_myCar_myCar'
 ******************************************************************************/





#define dT_VAL (ASD_DT_SCALED)
#define g_VAL (MyCCF_myCar_myCar_CAL_MEM.g)
#define myVehicle_REF (&(MyCCF_myCar_myCar.myVehicle))


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'MyCCF_myCar_myCar_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */
#define MyCCF_resources_CarMessages_bearing__MyCCF_myCar_myCar_Automatic_calc (MyCCF_resources_CarMessages_bearing)
#define MyCCF_resources_CarMessages_brake__MyCCF_myCar_myCar_Automatic_calc (MyCCF_resources_CarMessages_brake)
#define MyCCF_resources_CarMessages_power__MyCCF_myCar_myCar_Automatic_calc (MyCCF_resources_CarMessages_power)
#define MyCCF_resources_CarMessages_steering__MyCCF_myCar_myCar_Automatic_calc (MyCCF_resources_CarMessages_steering)
#define MyCCF_resources_CarMessages_v__MyCCF_myCar_myCar_Automatic_calc (MyCCF_resources_CarMessages_v)
#define MyCCF_resources_CarMessages_x__MyCCF_myCar_myCar_Automatic_calc (MyCCF_resources_CarMessages_x)
#define MyCCF_resources_CarMessages_y__MyCCF_myCar_myCar_Automatic_calc (MyCCF_resources_CarMessages_y)


void MyCCF_myCar_myCar_Automatic_calc (void)
{
   /* temp. variables */
   float32 _t1real32;

   MyCCF_myCar_myDrive_3_Automatic_move(myVehicle_REF, MyCCF_resources_CarMessages_power__MyCCF_myCar_myCar_Automatic_calc, MyCCF_resources_CarMessages_brake__MyCCF_myCar_myCar_Automatic_calc, dT_VAL, g_VAL * 1.01936799184506e-1F, MyCCF_resources_CarMessages_steering__MyCCF_myCar_myCar_Automatic_calc);
   _t1real32
      = ((MyCCF_myCar_myCar_RAM.myVehicle.v >= 0.0F) ? (((MyCCF_myCar_myCar_RAM.myVehicle.v <= 200.0F) ? MyCCF_myCar_myCar_RAM.myVehicle.v : 200.0F)) : 0.0F);
   MyCCF_resources_CarMessages_v__MyCCF_myCar_myCar_Automatic_calc
      = ((_t1real32 >= 0.0F) ? (((_t1real32 <= 200.0F) ? _t1real32 : 200.0F)) : 0.0F);
   MyCCF_resources_CarMessages_y__MyCCF_myCar_myCar_Automatic_calc = MyCCF_myCar_myCar_RAM.myVehicle.y;
   MyCCF_resources_CarMessages_bearing__MyCCF_myCar_myCar_Automatic_calc = MyCCF_myCar_myCar_RAM.myVehicle.bearing;
   MyCCF_resources_CarMessages_x__MyCCF_myCar_myCar_Automatic_calc = MyCCF_myCar_myCar_RAM.myVehicle.x;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'MyCCF_myCar_myCar_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



