/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.myCar
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCCF_MYCAR_MYCAR_AUTOMATIC_H_
#define _ASD_MYCCF_MYCAR_MYCAR_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "MyCCF_myCar_myDrive_3_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'MyCCF_myCar_myCar_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_myCar_Automatic_CAL_MEM_SUBSTRUCT {
   float32 g;
   struct MyCCF_myCar_myDrive_3_Automatic_CAL_MEM_SUBSTRUCT myVehicle;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'MyCCF_myCar_myCar_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'MyCCF_myCar_myCar_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_myCar_Automatic_RAM_SUBSTRUCT {
   struct MyCCF_myCar_myDrive_3_Automatic_RAM_SUBSTRUCT myVehicle;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'MyCCF_myCar_myCar_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'MyCCF_myCar_myCar_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_myCar_Automatic {
   struct MyCCF_myCar_myDrive_3_Automatic myVehicle;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'MyCCF_myCar_myCar_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ................MyCCF_myCar_myCar_Automatic */
#define _MyCCF_myCar_myCar_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'MyCCF_myCar_myCar_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct MyCCF_myCar_myCar_Automatic_CAL_MEM_SUBSTRUCT MyCCF_myCar_myCar_CAL_MEM;

/* forward declaration of substruct variable 'MyCCF_myCar_myCar_RAM' */
/* containing 'RAM' memory class tree */
extern struct MyCCF_myCar_myCar_Automatic_RAM_SUBSTRUCT MyCCF_myCar_myCar_RAM;

/* forward declaration of component variable 'MyCCF_myCar_myCar' */
/* containing 'ROM' memory class tree */
extern const struct MyCCF_myCar_myCar_Automatic MyCCF_myCar_myCar;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module MyCCF_myCar_myCar_Automatic
 ******************************************************************************/
extern void MyCCF_myCar_myCar_Automatic_calc (void);



#endif /* _ASD_MYCCF_MYCAR_MYCAR_AUTOMATIC_H_ */
