/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.MyTurn
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCCF_MYCAR_MYTURN_AUTOMATIC_PRIVATE
#define ESDL_MYCCF_MYCAR_MYTURN_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define x_VAL self->MyCCF_myCar_MyTurn_Automatic_RAM->x
#define y_VAL self->MyCCF_myCar_MyTurn_Automatic_RAM->y
#define bearing_VAL self->MyCCF_myCar_MyTurn_Automatic_RAM->bearing
#define D_VAL self->MyCCF_myCar_MyTurn_Automatic_CAL_MEM->D
#define Lib_VAL self->Lib
#define Lib_REF &(self->Lib)
#define dpi_VAL self->MyCCF_myCar_MyTurn_Automatic_RAM->dpi
#define pi_VAL self->MyCCF_myCar_MyTurn_Automatic_RAM->pi
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCCF_MYCAR_MYTURN_AUTOMATIC_PRIVATE */

