/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.resources.CarMessages
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "MyCCF_resources_CarMessages_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'MyCCF_resources_CarMessages'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/






/******************************************************************************
 * BEGIN: DEFINITION OF MESSAGES
 * ----------------------------------------------------------------------------
 * Total size is [bytes]:........................32
 * ---------------------------------------------------------------------------*/
/* messages of memory class:............................................'RAM' */
/* messages of size [bytes]:................................................4 */
/* modelled as 'MyCCF_resources_CarMessages_bearing' */
float32 MyCCF_resources_CarMessages_bearing = 0.0F;
/* modelled as 'MyCCF_resources_CarMessages_brake' */
float32 MyCCF_resources_CarMessages_brake = 0.0F;
/* modelled as 'MyCCF_resources_CarMessages_power' */
float32 MyCCF_resources_CarMessages_power = 0.0F;
/* modelled as 'MyCCF_resources_CarMessages_steering' */
float32 MyCCF_resources_CarMessages_steering = 0.0F;
/* modelled as 'MyCCF_resources_CarMessages_time' */
float32 MyCCF_resources_CarMessages_time = 0.0F;
/* modelled as 'MyCCF_resources_CarMessages_v' */
float32 MyCCF_resources_CarMessages_v = 0.0F;
/* modelled as 'MyCCF_resources_CarMessages_x' */
float32 MyCCF_resources_CarMessages_x = 0.0F;
/* modelled as 'MyCCF_resources_CarMessages_y' */
float32 MyCCF_resources_CarMessages_y = 0.0F;
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MESSAGES
 ******************************************************************************/



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



