/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.ACC
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCCF_MYCAR_ACC_AUTOMATIC_H_
#define _ASD_MYCCF_MYCAR_ACC_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'MyCCF_myCar_ACC_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_ACC_Automatic_RAM_SUBSTRUCT {
   float32 brake;
   uint8 accOn;
   uint8 on;
   uint8 sm;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'MyCCF_myCar_ACC_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'MyCCF_myCar_ACC_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_ACC_Automatic {
   struct MyCCF_myCar_ACC_Automatic_RAM_SUBSTRUCT * MyCCF_myCar_ACC_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'MyCCF_myCar_ACC_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..................MyCCF_myCar_ACC_Automatic */
#define _MyCCF_myCar_ACC_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class MyCCF_myCar_ACC_Automatic
 ******************************************************************************/
extern void MyCCF_myCar_ACC_Automatic_aCCStatemachineTrigger ( const struct MyCCF_myCar_ACC_Automatic * self);



#endif /* _ASD_MYCCF_MYCAR_ACC_AUTOMATIC_H_ */
