/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.resources.DriverMessages
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCCF_RESOURCES_DRIVERMESSAGES_AUTOMATIC_H_
#define _ASD_MYCCF_RESOURCES_DRIVERMESSAGES_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/* component structure for module MYCCF_RESOURCES_DRIVERMESSAGES_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...MyCCF_resources_DriverMessages_Automatic */
#define _MyCCF_resources_DriverMessages_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module MyCCF_resources_DriverMessages_Automatic
 ******************************************************************************/


/* declaration of messages */
extern float32 MyCCF_resources_DriverMessages_brake;
extern uint8 MyCCF_resources_DriverMessages_decrement;
extern uint8 MyCCF_resources_DriverMessages_display;
extern uint8 MyCCF_resources_DriverMessages_increment;
extern uint8 MyCCF_resources_DriverMessages_on;
extern float32 MyCCF_resources_DriverMessages_power;
extern float32 MyCCF_resources_DriverMessages_soll;


#endif /* _ASD_MYCCF_RESOURCES_DRIVERMESSAGES_AUTOMATIC_H_ */
