/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.Driver
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "MyCCF_myCar_Driver_Automatic.h"
#include "MyCCF_resources_DriverMessages_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'MyCCF_myCar_Driver_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'MyCCF_myCar_Driver'
 * data set:.....................................'MYCCF_MYCAR_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_Driver_Automatic_CAL_MEM_SUBSTRUCT MyCCF_myCar_Driver_CAL_MEM = {
   /* struct element:'MyCCF_myCar_Driver_CAL_MEM.brake' (modeled as:'brake.MyCCF_myCar_Driver') */
   0.0F,
   /* struct element:'MyCCF_myCar_Driver_CAL_MEM.controlACC' (modeled as:'controlACC.MyCCF_myCar_Driver') */
   false
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'MyCCF_myCar_Driver_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'MyCCF_myCar_Driver'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/





#define brake_VAL (MyCCF_myCar_Driver_CAL_MEM.brake)
#define controlACC_VAL (MyCCF_myCar_Driver_CAL_MEM.controlACC)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'MyCCF_myCar_Driver_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */
#define MyCCF_resources_DriverMessages_brake__MyCCF_myCar_Driver_Automatic_calc (MyCCF_resources_DriverMessages_brake)
#define MyCCF_resources_DriverMessages_on__MyCCF_myCar_Driver_Automatic_calc (MyCCF_resources_DriverMessages_on)


void MyCCF_myCar_Driver_Automatic_calc (void)
{
   MyCCF_resources_DriverMessages_on__MyCCF_myCar_Driver_Automatic_calc = controlACC_VAL;
   MyCCF_resources_DriverMessages_brake__MyCCF_myCar_Driver_Automatic_calc = brake_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'MyCCF_myCar_Driver_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



