/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................MyCCF.myCar.Control
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "MyCCF_myCar_Control_Automatic.h"
#include "MyCCF_resources_DriverMessages_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'MyCCF_myCar_Control_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'MyCCF_myCar_Control'
 * data set:.....................................'MYCCF_MYCAR_CONTROL_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct MyCCF_myCar_Control_Automatic_RAM_SUBSTRUCT MyCCF_myCar_Control_RAM = {
   /* substruct: MyCCF_myCar_Control_RAM.ACC_instance (modeled as:'ACC_instance.MyCCF_myCar_Control') */
   {
      /* struct element:'MyCCF_myCar_Control_RAM.ACC_instance.brake' (modeled as:'brake.ACC_instance.MyCCF_myCar_Control') */
      0.0F,
      /* struct element:'MyCCF_myCar_Control_RAM.ACC_instance.accOn' (modeled as:'accOn.ACC_instance.MyCCF_myCar_Control') */
      false,
      /* struct element:'MyCCF_myCar_Control_RAM.ACC_instance.on' (modeled as:'on.ACC_instance.MyCCF_myCar_Control') */
      false,
      /* struct element:'MyCCF_myCar_Control_RAM.ACC_instance.sm' (modeled as:'sm.ACC_instance.MyCCF_myCar_Control') */
      0U /* Off */
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'MyCCF_myCar_Control_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'MyCCF_myCar_Control'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'MyCCF_myCar_Control'
 * data set:.....................................'MYCCF_MYCAR_CONTROL_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct MyCCF_myCar_Control_Automatic MyCCF_myCar_Control = {
   /* substruct: MyCCF_myCar_Control.ACC_instance (modeled as:'ACC_instance.MyCCF_myCar_Control') */
   {
      /* type descriptor pointer 'MyCCF_myCar_ACC_Automatic_RAM' for memory class substruct for 'RAM' */
      &MyCCF_myCar_Control_RAM.ACC_instance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'MyCCF_myCar_Control'
 ******************************************************************************/





#define ACC_instance_REF (&(MyCCF_myCar_Control.ACC_instance))


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'MyCCF_myCar_Control_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */
#define MyCCF_resources_DriverMessages_brake__MyCCF_myCar_Control_Automatic_calc (MyCCF_resources_DriverMessages_brake)
#define MyCCF_resources_DriverMessages_display__MyCCF_myCar_Control_Automatic_calc (MyCCF_resources_DriverMessages_display)
#define MyCCF_resources_DriverMessages_on__MyCCF_myCar_Control_Automatic_calc (MyCCF_resources_DriverMessages_on)


void MyCCF_myCar_Control_Automatic_calc (void)
{
   MyCCF_myCar_ACC_Automatic_aCCStatemachineTrigger(ACC_instance_REF);
   MyCCF_myCar_Control_RAM.ACC_instance.on
      = MyCCF_resources_DriverMessages_on__MyCCF_myCar_Control_Automatic_calc;
   MyCCF_myCar_Control_RAM.ACC_instance.brake
      = MyCCF_resources_DriverMessages_brake__MyCCF_myCar_Control_Automatic_calc;
   MyCCF_resources_DriverMessages_display__MyCCF_myCar_Control_Automatic_calc = MyCCF_myCar_Control_RAM.ACC_instance.accOn;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'MyCCF_myCar_Control_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



